services:
  mongodb:
    image: mongo:latest
    container_name: stocksync-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: stocksync-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/stocksync
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: inventory-ui
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongodb_data:
